### ISSUE TITLE
Issues with parsing Mintos

### ISSUE THREAD

**Issue by pat-s** [ChrisRBe/PP-P2P-Parser#210]
Thanks for this effort! 👍  Hoping for some P2P automation soon :)

Mintos provides .xlsx files for download.

I converted them to .csv with `;` as column separator and `,` as decimal seperator. To me, the file looks similar to your `src/test/mintos.csv`.

However, parsing it leads to an output without content, only the header is written.
Is there anything I am doing wrong?

python 3.7.7

Here is a sample file:

**Edited with interest lines**

```
Transaction ID;Date;Details;Turnover;Balance;Currency
1861977623;2020-05-05 09:18:08;Deposits; 50,000000000;50,0000000;EUR
1862112425;2020-05-05 11:14:03;Loan 22742301-01 - investment in loan;-10,000000000;40,0000000;EUR
1862112428;2020-05-05 11:14:04;Loan 23125713-01 - investment in loan;-10,000000000;30,0000000;EUR
1862112431;2020-05-05 11:14:05;Loan 30736058-01 - investment in loan;-10,000000000;20,0000000;EUR
1862112457;2020-05-05 11:14:06;Loan 30837110-01 - investment in loan;-10,000000000;10,0000000;EUR
1862112460;2020-05-05 11:14:07;Loan 31320137-01 - investment in loan;-10,000000000; 0,0000000;EUR
1864297148;2020-05-06 02:48:56;Loan 23125713-01 - principal received;  0,278967768; 0,2789678;EUR
1864297091;2020-05-06 02:48:56;Loan 23125713-01 - interest received;  0,002222222; 0,2811900;EUR
1886919551;2020-05-13 00:08:59;Loan 23125713-01 - principal received;  0,280497756; 0,5616877;EUR
1886919491;2020-05-13 00:08:59;Loan 23125713-01 - interest received;  0,015121606; 
```

**Comment by ChrisRBe** [comment]
Hey @pat-s,

Just setting up a python env on my new PC to try and look what's going on. 
Do you know if you have any interest (Zinsen) already received from Mintos? 
I'm not entirely sure right now if the parser is ignoring all invest statements and only outputs interest lines. 
Will check on my side.

**Comment by pat-s** [comment]
Ah! Did not know that it only parses interests. So far I have no interests, just investments.

Just wondering: Shouldn't it be able to parse all types for a successful automation within PP? Or is this a known limitation?

While writing this another thought: Does it account for redundant entries? Let's say I parse and import the same csv twice - it will be imported twice?
Accounting for such cases would remove the need to track which dates were already imported (sorry, that should be a new issue actually).

**Comment by ChrisRBe** [comment]
Hey,

I will try and answer all questions as best as I can.


> Ah! Did not know that it only parses interests. So far I have no interests, just investments.
> 
> Just wondering: Shouldn't it be able to parse all types for a successful automation within PP? Or is this a known limitation?

Well. It is doing what I told it to do 😂 Kidding aside. I am handling Mintos, and the other p2p sites as "normal" accounts in PP. That way I have an initial investment that generates interest. When I started working on this script I was not interested in tracking all investements/paybacks and so on. Only interest and additional site payments were of interest to me. That should be reflected in the parsing result. I followed a bit the discussion on the Portfolio Performance Discourse and this was the opinion of at least a few people there (Ignore investements in loans, etc. and only have the interest payouts in PP).


> While writing this another thought: Does it account for redundant entries? Let's say I parse and import the same csv twice - it will be imported twice?
> Accounting for such cases would remove the need to track which dates were already imported (sorry, that should be a new issue actually).

This is more a question on Portfolio Performance side. My script is hmm... let's call it stupid :). It parses a given file and creates a csv file that can be parsed by Portfolio Performance. The script has no knowledge of the PP database and outputs what it finds in the original data. Portfolio Performance import feature on the other hand is capable of identifying duplicate entries and will ignore already existing entries from the import list.

**Comment by pat-s** [comment]
> Portfolio Performance import feature on the other hand is capable of identifying duplicate entries and will ignore already existing entries from the import list.

Ah great! So then I can automate this every once in a while without having to fear to include duplicate ones.

>  I followed a bit the discussion on the Portfolio Performance Discourse and this was the opinion of at least a few people there (Ignore investments in loans, etc. and only have the interest payouts in PP).

Fair enough. Maybe that's even the right way to do it. I will see how it goes in the next months - new to P2P so far :)

---

Regarding parsing interests: I've added a few interest lines into the file in the first post. Does this help? I assume the "interest" lines should be parsed?

**Comment by ChrisRBe** [comment]
> Regarding parsing interests: I've added a few interest lines into the file in the first post. Does this help? I assume the "interest" lines should be parsed?

I see the issue.. Looks like mintos changed their account statement format. I pushed a change to hopefully have them parse again.

**Comment by pat-s** [comment]
Thanks, works now! 👍
