### ISSUE TITLE
Importfehler bei sehr kleinen Zinszahlung

### ISSUE THREAD

**Issue by chrsthln** [ChrisRBe/PP-P2P-Parser#267]
Beim Test des Parsers ist mir aufgefallen, dass sehr kleine Beträge zu Fehlbuchungen in PP führen. 
Eine Buchung über 0,000041275€ führte in PP bspw. zu einer Buchung von 4,13€ als Zinszahlung. 
![image](https://user-images.githubusercontent.com/77150959/104007327-0e3a7600-51a8-11eb-9cb1-3e7dba01666d.png)

[Beispielbuchungen.zip](https://github.com/ChrisRBe/PP-P2P-Parser/files/5786749/Beispielbuchungen.zip)

**Comment by ChrisRBe** [comment]
Hi @chrsthln,
ich werde versuchen am WE mal reinzuschauen. RL ueberrollt mich gerade.

**Comment by AlexanderLill** [comment]
Hi,

bei mir tauchen in der CSV datei Einträge wie dieser hier auf:
```
2021-01-15,"1,247e-06",EUR,Zinsen,-123: Loan 123-01 - interest received
```

Ich schaetze dass PP beim Import mit diesen sehr kleinen Zahlen durch das Format ein Problem hat. Kann man die Zahlen vielleicht vor dem Schreiben in die CSV Datei formattieren zu einem `##,##` Format?

**Comment by AlexanderLill** [comment]
Ich habe versucht, es in folgendem Pull Request zu korrigieren :)
https://github.com/ChrisRBe/PP-P2P-Parser/pull/269

**Comment by ChrisRBe** [comment]
Hallo @AlexanderLill, @chrsthln 

Ich habe gestern in den release notes von PP gesehen, dass beim importieren jetzt eh nur bis zur 8. Stelle unterstützt wird.
Ich hatte lokal schon mal was ausprobiert, aber noch nicht wirklich was geschrieben.

@AlexanderLill Ich schau mir deinen PR gleich an.

**Comment by ChrisRBe** [comment]
So. #269 ist gemergt. @chrsthln und @AlexanderLill koennt ihr mal schauen, ob jetzt alles wie erwartet funktioniert?

**Comment by chrsthln** [comment]
Hey @ChrisRBe, nun funktioniert es einwandfrei. Vielen Dank euch beiden. 👍
