### ISSUE TITLE
Mintos Import: Summe Website & PP unterschiedlich

### ISSUE THREAD

**Issue by AlexanderLill** [ChrisRBe/PP-P2P-Parser#268]
Hallo,

erst einmal vielen Dank für das Schreiben des Parsers, ich bin absolut begeistert! 👍 

Mir ist beim Import von Daten von Mintos aufgefallen, dass die berechnete Summe in PP nicht mit der Summe auf der Website übereinstimmt. Ich denke das liegt zum einen daran, dass gewisse Transaktionen nicht richtig klassifiziert werden, und zum anderen verstehe ich noch nicht ganz, wie Mintos die Zahl auf der Website ausrechnet.

Ich habe einige fehlende Transaktionen gefunden und das `.yaml` File entsprechend angepasst. Leider ist meine Endsumme immer noch falsch. In jedem Fall wollte ich meine geupdateten RegExes hier mal zur Diskussion stellen.

```
  deposit: "(Deposits)|(^Incoming client.*)|(^Incoming currency exchange.*)|(^Affiliate partner bonus$)"
  withdraw: "(^Withdraw application.*)|(Outgoing currency.*)|(Withdrawal)"
  interest: "(^Delayed interest.*)|(^Late payment.*)|(^Interest income.*)|(^Cashback.*)|(^.*[Ii]nterest received.*)|(^.*late fees received$)"
  fee: "(^FX commission.*)|(.*secondary market fee$)|(.*discount/premium.*)"
```

Das Problem bei den `discount/premium` Einträgen ist, dass sie ggf. auch Positiv sein könnten, also eher als Zinsen oder Einlagen gesehen werden könnten, falls auf dem Zweitmarkt etwas mit Gewinn verkauft werden konnte. Bei Rabatten ist der Wert dieser Transaktionen negativ.

**Comment by ChrisRBe** [comment]
Vielen Dank erstmal für die aktualisierten Strings. Ich hatte eigentlich den parser etwas schlauer machen wollen und sämtliche unbekannten Typen, die nicht gematcht werden, in ein log file zu schreiben. Das könnte eine Analyse vielleicht etwas erleichtern um herauszufinden, welche reg exes noch fehlen.
Leider ändern sich die strings auch gerne mal... Das macht das ganze etwas umständlicher.

**Comment by ChrisRBe** [comment]
Vielleicht finde ich am Wochenende mal die Zeit, das Logging dahingehend zu verbessern, dass die Einträge, die keinem Transaktionstypen zugeordnet werden können in eine Log Datei geschrieben werden.
Ich muss mir den Teil des Codes nochmal anschauen.

**Comment by AlexanderLill** [comment]
Hi @ChrisRBe, ich habe schon einmal angefangen (siehe Branch in meinem Fork), warte aber noch auf Feedback vom Mintos Support wieso meine in Portfolio Performance berechnete Summe nicht mit dem Betrag auf der Website übereinstimmt.

Ich melde mich hier bzw. erstelle einen Pull Request, sobald es etwas neues gibt.

https://github.com/AlexanderLill/PP-P2P-Parser/tree/mintos_extended_parsing

**Comment by ChrisRBe** [comment]
Hi @AlexanderLill 
das sieht ja im ersten Ansatz schon mal vielversprechend aus. Ich habe dir ein paar Kommentare in den PR geschrieben :)

**Comment by ChrisRBe** [comment]
Ich werde das Issue erst mal schliessen. Falls es hier noch Fehler geben sollte, mach bitte ein Neues auf.
