### ISSUE TITLE
Dependency installation conflict

### ISSUE THREAD

**Issue by pat-s** [ChrisRBe/PP-P2P-Parser#302]
```
pip3 install -r requirements.txt

ERROR: Cannot install -r requirements.txt (line 15) and astroid==2.5.6 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested astroid==2.5.6
    pylint 2.5.2 depends on astroid<=2.5 and >=2.4.0
```

**Comment by ChrisRBe** [comment]
hmm. let me see if I can fix this easily. 
I have mostly switched to use pipenv nowadays on my PCs.

**Comment by ChrisRBe** [comment]
Please have a look with the latest master branch commit. Updated the requirements.txt file to the latest versions :)

**Comment by pat-s** [comment]
Thanks. I did not get an error anymore but seeing

```
INFO: pip is looking at multiple versions of regex to determine which version is compatible with other requirements. This could take a while.
```

which did not finish after 10 mins.

**Comment by ChrisRBe** [comment]
huh. Possibly caused by some other out of date dependencies on the requirements.txt? I did find some other reports about this pip behaviour. Let's see.

**Comment by pat-s** [comment]
Not so urgent, I managed to get all requirements in some other way. But others might struggle more, so probably worth fixing :)

**Comment by ChrisRBe** [comment]
Not too sure if there's anything I can do here. I would rather like to get rid of the requirements.txt file at some point.
