### ISSUE TITLE
Hardcoded python interpreter in `parse-account-statements.py`

### ISSUE THREAD

**Issue by pat-s** [ChrisRBe/PP-P2P-Parser#303]
Not a python dev and maybe this best practice but I am using `/usr/local/bin/python3` on macOS as my default `python3` and packages installed via this interpreter are not available for `/usr/bin/python3`.

Is there a way to force use `/usr/local/bin/python3` for execution instead of the one defined within the script?

**Comment by ChrisRBe** [comment]
Hi @pat-s 
do you know if you have /usr/bin/env on macOS? According to https://apple.stackexchange.com/questions/297533/does-macos-have-usr-bin-env it should be available.

Could you check what happens if you replace the shebang like this

**Comment by ChrisRBe** [comment]
merged #304 now that should address this issue.

**Comment by pat-s** [comment]
> do you know if you have /usr/bin/env on macOS?

Yes.

Sorry for getting back so late. Thanks for addressing this!
