### ISSUE TITLE
Mintos import with monthly aggregate does not work

### ISSUE THREAD

**Issue by thomas292** [ChrisRBe/PP-P2P-Parser#477]
Mintos import with monthly aggregate does not work with current version 1.2.1 and master version. 

Error message is parse-account-statements.py: error: unrecognized arguments: --aggregate monthly

**Comment by ChrisRBe** [comment]
Hi @thomas292, 
will have a look.

**Comment by ChrisRBe** [comment]
Hi @thomas292,
Initial tests on my end show no problem with latest master using the included test data:

```
PS C:\Users\cb\PycharmProjects\PP-P2P-Parser> python .\parse-account-statements.py .\src\test\testdata\mintos_several_months.csv --aggregate monthly --type mintos --debug
INFO:Aggregating data on a monthly basis
INFO:Config ini
DEBUG:Unexpected statement:
DEBUG:Unexpected statement:
DEBUG:Unexpected statement:
DEBUG:Unexpected statement:
DEBUG:entry type is Einlage. new entry date is 2018-02-28
DEBUG:entry type is Einlage. new entry date is 2018-01-31
DEBUG:Unexpected statement:
DEBUG:Unexpected statement:
DEBUG:Unexpected statement:
DEBUG:Unexpected statement:
DEBUG:Unexpected statement:
DEBUG:entry type is Zinsen. new entry date is 2018-01-31
DEBUG:Unexpected statement:
DEBUG:entry type is Zinsen. new entry date is 2018-01-31
DEBUG:add to existing entry
DEBUG:entry type is Zinsen. new entry date is 2018-01-31
DEBUG:add to existing entry
DEBUG:Unexpected statement:
```

What environment are you using to run the script? (Linux, Mac, Windows, requirements.txt, pipenv, ... ?)

**Comment by ChrisRBe** [comment]
I created #478 to extend the logging done. This PR also refactors the argument parsing section. Not too sure what could be causing this on your end.

**Comment by thomas292** [comment]
Dear @ChrisRBe,

I'm running a Mac OS installation. I retried it, after your feedback and got it working. I might have used an old version of the code snippet. Thank you for your valueable support.

**Comment by ChrisRBe** [comment]
Fantastic :) Glad it's working now. Hope it helps. Thank you for using this little tool.
